SnowRentals/SnowRentals/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import sprzet, klient, wypozyczenie, utarg

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('sprzet/', sprzet, name='sprzet'),
    path('klient/', klient, name='klient'),
    path('wypozyczenie/', wypozyczenie, name='wypozyczenie'),
    path('utarg/', utarg, name='utarg'),
    path('admin/', admin.site.urls),
]

SnowRentals/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('kontakt/', views.kontakt, name='kontakt'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

SnowRentals/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('nowySprzet/', views.nowySprzet, name="nowySprzet"),
    path('nowyKlient/', views.nowyKlient, name="nowyKlient"),
    path('noweWypozyczenie/', views.noweWypozyczenie, name="noweWypozyczenie"),
    path('nowyPakiet/', views.nowyPakiet, name="nowyPakiet"),
    path('sprzet/<int:pk>/', views.sprzet_szczegol, name="sprzet_szczegol"),
    path('sprzet/<int:pk>/delete/', views.delete, name="delete"),
    path('klient/<int:pk>/', views.klient_szczegol, name="klient_szczegol"),
    path('wypozyczenie/<int:pk>/', views.wypozyczenie_szczegol, name="wypozyczenie_szczegol"),
    path('klient/<int:pk>/edytuj_klient/', views.edytuj_klient, name="edytuj_klient"),
    path('wypozyczenie/<int:pk>/edytuj_wypozyczenie/', views.edytuj_wypozyczenie, name="edytuj_wypozyczenie"),
    path('sprzet/<int:pk>/edytuj_sprzet/', views.edytuj_sprzet, name="edytuj_sprzet"),
]

SnowRentals/item/forms.py
from django import forms
from django.contrib.admin.widgets import AdminDateWidget, AdminSplitDateTime
from django.forms.widgets import SelectDateWidget


from .models import Pracownik, Pakiet, Sprzet, Klient, Wypozyczenie

INPUT_CLASSES = 'w-1/6 py-3 px-4 rounded-xl border'

class NowySprzetForm(forms.ModelForm):
    class Meta:
        model = Sprzet
        fields = ('rodzaj', 'dlugosc', 'marka', 'stan', 'cena', 'wypozyczone',)

        widgets = {
            'rodzaj': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'dlugosc': forms.NumberInput(attrs={
                'class': INPUT_CLASSES
            }),
            'marka': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'stan': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'cena': forms.NumberInput(attrs={
                'class': INPUT_CLASSES
            }),
            'wypozyczone': forms.Select(attrs={
                'class': INPUT_CLASSES
            })
        }


class NowyKlientForm(forms.ModelForm):
    class Meta:
        model = Klient
        fields = ('imie', 'nazwisko', 'PESEL', 'miasto', 'ulica_nrDomu', 'kod_pocztowy', 'nr_telefonu',)


        widgets = {
            'imie': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'nazwisko': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'PESEL': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'miasto': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'ulica_nrDomu': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'kod_pocztowy': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'nr_telefonu': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class EdytujKlientForm(forms.ModelForm):
    class Meta:
        model = Klient
        fields = ('imie', 'nazwisko', 'PESEL', 'miasto', 'ulica_nrDomu', 'kod_pocztowy', 'nr_telefonu',)


        widgets = {
            'imie': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'nazwisko': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'PESEL': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'miasto': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'ulica_nrDomu': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'kod_pocztowy': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            }),
            'nr_telefonu': forms.TextInput(attrs={
                'class': INPUT_CLASSES
            })
        }

class NoweWypozyczenieForm(forms.ModelForm):
    class Meta:
        model = Wypozyczenie
        fields = ('klient', 'do',)

        widgets = {
            'klient': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'do': SelectDateWidget(attrs={
                'class': 'w-1/6 py-2 px-2 rounded-xl border'
            }),
        }

class EdytujWypozyczenieForm(forms.ModelForm):
    class Meta:
        model = Wypozyczenie
        fields = ('do', 'zaplacone',)

        widgets = {
            'do': SelectDateWidget(attrs={
                'class': 'w-1/6 py-2 px-2 rounded-xl border'
            }),
            'zaplacone': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
        }

class NowyPakietForm(forms.ModelForm):
    class Meta:
        model = Pakiet
        fields = ('sprzet', 'wypozyczenie',)

        widgets = {
            'sprzet': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'wypozyczenie': forms.Select(attrs={
                'class': INPUT_CLASSES
            })
        }


class EdytujSprzetForm(forms.ModelForm):
    class Meta:
        model = Sprzet
        fields = ('stan', 'cena', 'wypozyczone',)

        widgets = {
            'stan': forms.Select(attrs={
                'class': INPUT_CLASSES
            }),
            'cena': forms.NumberInput(attrs={
                'class': INPUT_CLASSES
            }),
            'wypozyczone': forms.Select(attrs={
                'class': INPUT_CLASSES
            })
        }

SnowRentals/item/views.py
import datetime

import numpy as np
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.db import transaction

from .models import Sprzet, Klient, Wypozyczenie, Pakiet, BOOL, Utarg
from .forms import NowySprzetForm, NowyKlientForm, NoweWypozyczenieForm, NowyPakietForm, EdytujKlientForm, EdytujWypozyczenieForm, EdytujSprzetForm

TAK = get_object_or_404(BOOL, pk=1)
NIE = get_object_or_404(BOOL, pk=2)

def sprzet_szczegol(request, pk):  #szczegóły sprzętu
    item = get_object_or_404(Sprzet, pk=pk)

    return render(request, 'item/sprzet_szczegol.html',{
        'item': item
    })

def klient_szczegol(request, pk):  #szczegóły klientów
    item = get_object_or_404(Klient, pk=pk)

    return render(request, 'item/klient_szczegol.html',{
        'item': item
    })

def wypozyczenie_szczegol(request, pk):  #szczegóły wypozyczenia
    item = get_object_or_404(Wypozyczenie, pk=pk)
    pakiet = Pakiet.objects.filter(wypozyczenie=item.pk)

    return render(request, 'item/wypozyczenie_szczegol.html',{
        'item': item,
        'pakiet': pakiet
    })

@login_required()
def nowySprzet(request):
    if request.method == 'POST':
        form=NowySprzetForm(request.POST)

        if form.is_valid():
            item = form.save(commit=False) #do wypożyczenia
            if str(item.stan) == "Bardzo dobry":
                item.cena = np.floor(item.cena * 1)
            if str(item.stan) == "Dobry":
                item.cena = np.floor(item.cena * 0.9)
            elif str(item.stan) == "Jeszcze sprawny":
                item.cena = np.floor(item.cena * 0.85)
            elif str(item.stan) == "Nie sprawny":
                item.cena = np.floor(item.cena * 0.7)
            item.save()

            return redirect('item:sprzet_szczegol', pk=item.id)

    form = NowySprzetForm()

    return render(request, 'item/form.html',{
        'form': form,
        'title': 'Nowy sprzęt',
    })

@login_required()
def edytuj_sprzet(request, pk):
    item = get_object_or_404(Sprzet, pk=pk)

    if request.method == 'POST':
        form=EdytujSprzetForm(request.POST, instance=item)

        if form.is_valid():
            item = form.save(commit=False)  # do wypożyczenia
            if str(item.stan) == "Bardzo dobry":
                item.cena = np.floor(item.cena * 1)
            if str(item.stan) == "Dobry":
                item.cena = np.floor(item.cena * 0.9)
            elif str(item.stan) == "Jeszcze sprawny":
                item.cena = np.floor(item.cena * 0.85)
            elif str(item.stan) == "Nie sprawny":
                item.cena = np.floor(item.cena * 0.7)
            item.save()

            return redirect('item:sprzet_szczegol', pk=item.id)

    form = EdytujSprzetForm(instance=item)

    return render(request, 'item/form.html',{
        'form': form,
        'title': 'Edytuj sprzęt',
    })

@login_required()
@transaction.atomic()
def noweWypozyczenie(request):
    if request.method == 'POST':
        form = NoweWypozyczenieForm(request.POST)

        if form.is_valid():
            item = form.save(commit=False)
            item.od = datetime.date.today()
            item.pracownik = request.user
            item.zaplacone = NIE
            item.save()

            return redirect('item:wypozyczenie_szczegol', pk=item.id)

    form = NoweWypozyczenieForm()

    return render(request, 'item/form.html',{
        'form': form,
        'title': 'Nowe wypożyczenie',
    })

@login_required()
def edytuj_wypozyczenie(request, pk):

    item = get_object_or_404(Wypozyczenie, pk=pk)
    if request.method == 'POST':
        form = EdytujWypozyczenieForm(request.POST, instance=item)

        if form.is_valid():
            editedItem = form.save(commit=False)
            if editedItem.zaplacone == TAK:
                pakiet = Pakiet.objects.filter(wypozyczenie=item.id)

                dzis = datetime.date.today()

                if dzis > editedItem.do:
                    utarg =get_object_or_404(Utarg, data=dzis)
                    utarg.kwota = utarg.kwota + 10
                    utarg.save()

                #roz = int(dzis - editedItem.do)
                # if roz >0:
                #     utarg = get_object_or_404(Utarg, data=dzis)
                #     for i in range(roz-1):
                #         utarg.kwota = utarg.kwota + 10



                for x in pakiet:
                    sprzet_id = x.sprzet.id
                    sprzet = get_object_or_404(Sprzet, pk=sprzet_id)
                    sprzet.wypozyczone = NIE
                    sprzet.save()

                editedItem.save()
                return redirect('item:wypozyczenie_szczegol', pk=item.id)
            elif editedItem.zaplacone == NIE:
                form.save()
                return redirect('item:wypozyczenie_szczegol', pk=item.id)

    form = EdytujWypozyczenieForm(instance=item)

    return render(request, 'item/form.html',{
        'form': form,
        'title': 'Edytuj wypożyczenie',
    })

@login_required()
def nowyKlient(request):
    if request.method == 'POST':
        form = NowyKlientForm(request.POST)

        if form.is_valid():
            item = form.save(commit=False)
            item.save()

            return redirect('item:klient_szczegol', pk=item.id)

    form = NowyKlientForm()

    return render(request, 'item/form.html',{
        'form': form,
        'title': 'Nowy klient',
    })

@login_required()
def edytuj_klient(request, pk):
    item = get_object_or_404(Klient, pk=pk)

    if request.method == 'POST':
        form = EdytujKlientForm(request.POST, instance=item)

        if form.is_valid():
            form.save()

            return redirect('item:klient_szczegol', pk=item.id)

    form = EdytujKlientForm(instance=item)

    return render(request, 'item/form.html',{
        'form': form,
        'title': 'Edytuj klient',
    })

@login_required()
@transaction.atomic()
def nowyPakiet(request):
    if request.method == 'POST':
        form = NowyPakietForm(request.POST)

        if form.is_valid():
            item = form.save(commit=False)
            klucz = item.wypozyczenie.id
            sprzet_id = item.sprzet.id
            sprzet = get_object_or_404(Sprzet, pk=sprzet_id)

            data = datetime.date.today()
            utarg = Utarg.objects.all()

            if sprzet.wypozyczone == NIE:
                for x in utarg:
                    if x.data == data:
                        utarg = x
                        utarg.kwota = utarg.kwota + sprzet.cena
                        utarg.save()

                sprzet.wypozyczone = TAK

                item.save()
                sprzet.save()

                return redirect('item:wypozyczenie_szczegol', pk=klucz)
            else:
                return redirect('item:wypozyczenie_szczegol', pk=klucz) #tutaj może dorobię stronę

    form = NowyPakietForm()

    return render(request, 'item/form.html', {
        'form': form,
        'title': 'Pakiet',
    })

@login_required
def delete(request, pk):
    item = get_object_or_404(Sprzet, pk=pk)
    item.delete()

    return redirect('core:index')

SnowRentals/item/templates/item/form.html
{% extends 'core/base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">{{ title }}</h1>

<form method="post" action="." enctype="multipart/form-data">
    {% csrf_token %}

    <div class="space-y-4 px-4">
        {{ form.as_p }}
    </div>

    {% if form.errors or form.non_fiels_errors %}
        <div class="mb-3 p-4 bg-red-100 rounded-xl">
            {% for field in form %}
                {{ field.errors }}
            {% endfor %}

            {{ form.non_field_errors }}
        </div>
    {% endif %}
    <button class="mt-6 py-3 px-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Dodaj</button>
</form>
{% endblock %}

SnowRentals/item/templates/item/klient_szczegol.html
{% extends 'core/base.html' %}

{% block title %}{{ item.imie}} {{ item.nazwisko }}{% endblock %}

{% block content %}
<div style="text-align:center; width:50%; margin: 0 auto">
    <h2 class="p-4 text-3xl text-white bg-teal-500 rounded-t-xl"><strong>{{item.imie}} {{ item.nazwisko }}</strong></h2>
    <ul class="mb-4 p-4 text-xl bg-gray-300 rounded-b-xl">
        <li><strong>PESEL</strong>: {{ item.PESEL}}</li>
        <li><strong>Miasto</strong>: {{ item.miasto}}</li>
        <li><strong>Ulica / nr domu</strong>: {{ item.ulica_nrDomu}}</li>
        <li><strong>Kod pocztowy</strong>: {{ item.kod_pocztowy}}</li>
        <li><strong>Nr telefonu</strong>: {{ item.nr_telefonu}}</li>
    </ul>

    <a href="{% url 'item:edytuj_klient' item.id %}" class="inline-block mt-4 px-4 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Edytuj</a>
</div>
{% endblock %}

SnowRentals/item/templates/item/sprzet_szczegol.html
{% extends 'core/base.html' %}

{% block title %}{{ item.rodzaj}}{% endblock %}

{% block content %}
<div style="text-align:center; width:50%; margin: 0 auto">
    <h2 class="p-4 text-3xl text-white bg-teal-500 rounded-t-xl"><strong>{{item.rodzaj}}</strong></h2>
    <ul class="mb-4 p-4 text-xl bg-gray-300 rounded-b-xl">
        <li><strong>Marka</strong>: {{ item.marka}}</li>
        <li><strong>Długość / rozmiar</strong>: {{ item.dlugosc}}</li>
        <li><strong>Stan</strong>: {{ item.stan}}</li>
        <li><strong>Cena</strong>: {{ item.cena}}</li>
        <li><strong>Wypożyczone</strong>: {{ item.wypozyczone}}</li>
    </ul>

    <a href="{% url 'item:edytuj_sprzet' item.id %}" class="inline-block mt-4 px-4 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Edytuj</a>
    {% if request.user.is_staff %}
        <a href="{% url 'item:delete' item.id %}" class="inline-block mt-4 px-4 py-3 text-lg font-semibold bg-red-500 text-white hover:bg-red-700 rounded-xl">Usuń</a>
    {% endif %}
</div>
{% endblock %}

SnowRentals/item/templates/item/wypozyczenie_szczegol.html
{% extends 'core/base.html' %}

{% block title %}{{ item.}}{% endblock %}

{% block content %}
    <div style="text-align:center; width:50%; margin: 0 auto">
        <h2 class="p-4 text-3xl text-white bg-teal-500 rounded-t-xl"><strong>{{item.klient}}</strong></h2>
        <ul class="mb-4 p-4 text-xl bg-gray-300 rounded-b-xl">
            <li><strong>Pracownik</strong>: {{ item.pracownik }}</li>
            <li><strong>Od</strong>: {{ item.od}}</li>
            <li><strong>Do</strong>: {{ item.do}}</li>
            <li><strong>Zwrócone</strong>: {{ item.zaplacone }}</li>
        </ul>

        <a href="{% url 'item:edytuj_wypozyczenie' item.id %}" class="inline-block mt-4 px-4 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Edytuj</a>
        <a href="{% url 'item:nowyPakiet'%}" class="inline-block mt-4 px-4 py-3 text-lg font-semibold bg-teal-500 text-white hover:bg-teal-700 rounded-xl">Dobierz sprzęt</a>
    </div>

    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Powiązane sprzęty</h2>

            <div class="grid grid-cols-3 gap-3">
                {% for item in pakiet %}
                <div>
                    <a href="{% url 'item:sprzet_szczegol' item.sprzet.id %}">
                        <div class="p-4 bg-white rounded-xl">
                            <h2 class="text-xl">{{ item.sprzet.rodzaj }}</h2>
                            <p class="text-gray-500">Długość: {{ item.sprzet.dlugosc }}</p>
                            <p class="text-gray-500">Stan: {{ item.sprzet.stan }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
    </div>
{% endblock %}