SnowRentals/SnowRentals/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import sprzet, klient, wypozyczenie, utarg

urlpatterns = [
    path('', include('core.urls')),
    path('items/', include('item.urls')),
    path('sprzet/', sprzet, name='sprzet'),
    path('klient/', klient, name='klient'),
    path('wypozyczenie/', wypozyczenie, name='wypozyczenie'),
    path('utarg/', utarg, name='utarg'),
    path('admin/', admin.site.urls),
]

SnowRentals/core/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path, include

from . import views
from .forms import LoginForm

app_name = 'core'

urlpatterns = [
    path('', views.index, name='index'),
    path('kontakt/', views.kontakt, name='kontakt'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='core/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', views.logout_view, name='logout'),
]

SnowRentals/item/urls.py
from django.urls import path

from . import views

app_name = 'item'

urlpatterns = [
    path('nowySprzet/', views.nowySprzet, name="nowySprzet"),
    path('nowyKlient/', views.nowyKlient, name="nowyKlient"),
    path('noweWypozyczenie/', views.noweWypozyczenie, name="noweWypozyczenie"),
    path('nowyPakiet/', views.nowyPakiet, name="nowyPakiet"),
    path('sprzet/<int:pk>/', views.sprzet_szczegol, name="sprzet_szczegol"),
    path('sprzet/<int:pk>/delete/', views.delete, name="delete"),
    path('klient/<int:pk>/', views.klient_szczegol, name="klient_szczegol"),
    path('wypozyczenie/<int:pk>/', views.wypozyczenie_szczegol, name="wypozyczenie_szczegol"),
    path('klient/<int:pk>/edytuj_klient/', views.edytuj_klient, name="edytuj_klient"),
    path('wypozyczenie/<int:pk>/edytuj_wypozyczenie/', views.edytuj_wypozyczenie, name="edytuj_wypozyczenie"),
    path('sprzet/<int:pk>/edytuj_sprzet/', views.edytuj_sprzet, name="edytuj_sprzet"),
]

SnowRentals/core/models.py
from django.db import models

SnowRentals/core/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Nazwa użytkownika',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Podaj hasło',
        'class': 'w-full py-4 px-6 rounded-xl'
    }))

INPUT_CLASSES = 'w-1/2 py-4 px-6 rounded-xl'

class SignupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name',  'password1', 'password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Nazwa użytkownika',
        'class': INPUT_CLASSES
    }))

    first_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Imię pracownika',
        'class': INPUT_CLASSES
    }))

    last_name = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder': 'Nazwisko pracownika',
        'class': INPUT_CLASSES
    }))

    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Podaj hasło',
        'class': INPUT_CLASSES
    }))

    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Powtórz hasło',
        'class': INPUT_CLASSES
    }))

SnowRentals/core/views.py
from django.shortcuts import render, redirect, get_object_or_404

from item.models import Klient, Sprzet, Wypozyczenie, Utarg, Pakiet, BOOL

from .forms import SignupForm
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

def index(request):
    return render(request, 'core/index.html')

@login_required()
def sprzet(request):
    items = Sprzet.objects.all()
    return render(request, 'core/sprzet.html',{
        'items': items,
    })

@login_required()
def klient(request):
    items = Klient.objects.all()
    return render(request, 'core/klient.html',{
        'items':items,
    })

@login_required()
def wypozyczenie(request):
    TAK = get_object_or_404(BOOL, pk=1)
    NIE = get_object_or_404(BOOL, pk=2)

    items = Wypozyczenie.objects.all().filter(zaplacone=NIE)
    oddane = Wypozyczenie.objects.all().filter(zaplacone=TAK)
    return render(request, 'core/wypozyczenie.html',{
        'items': items,
        'oddane': oddane,
    })

def kontakt(request):
    return render(request, 'core/kontakt.html')

def signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect('/login/')
        else:
            form = SignupForm()
    form = SignupForm()

    return render(request, 'core/signup.html',{
        'form': form
    })

def utarg(request):
    item = Utarg.objects.all()

    return render(request, 'core/utarg.html',{
        'item': item,
    })

def logout_view(request):
    logout(request)
    return render(request, 'core/index.html')

SnowRentals/core/templates/core/base.html
<!doctype html>

<html>
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">

        <script src="https://cdn.tailwindcss.com"> </script>

        <title>{% block title %}{% endblock %} | SnowRentals</title>
    </head>

    <body>
        <nav class="px-5 py-5 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">SnowRentals</a>

            <div class="space-x-3">
                <a href="{% url 'sprzet' %}" class="text=lg font-semibold hover:text-gray-500">Sprzęt</a>
                <a href="{% url 'klient' %}" class="text=lg font-semibold hover:text-gray-500">Klienci</a>
                <a href="{% url 'wypozyczenie' %} " class="text=lg font-semibold hover:text-gray-500">Wypożyczenia</a>

                {% if request.user.is_authenticated %}
                    <a href="{% url 'item:nowyKlient' %}" class="px-3 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Nowy klient</a>
                    <a href="{% url 'item:noweWypozyczenie' %}" class="px-3 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Nowe wypożyczenie</a>
                    {% if request.user.is_staff %}
                        <a href="{% url 'item:nowySprzet' %}" class="px-3 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Nowy sprzęt</a>
                        <a href="{% url 'core:signup' %}" class="px-3 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Nowy pracownik</a>
                        <a href="{% url 'utarg' %}" class="px-3 py-3 text-lg font-semibold bg-teal-500 text-white rounded-xl hover:bg-gray-700">Utarg</a>
                    {% endif %}
                    <a href="{% url 'core:logout' %}" class="px-3 py-3 text-lg font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Wyloguj</a>
                {% else %}
                    <a href="{% url 'core:login' %}" class="px-5 py-5 text-xl font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Zaloguj się</a>
                {% endif %}


            </div>
        </nav>
        <div class="px-6 py-6">
            {% block content %}
            {% endblock %}
        </div>

        <footer class="py-5 px-5 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h1 class="mb-5 font-semibold text-gray-400">O nas</h1>
                <h2 class="mb-5 font-semibold text-gray-400">Projekt na przedmiot Bazy Danych.</h2>
                <p class="text-lg text-gray-500"> Strona do obsługi wypożyczalni sprzętu zimowego, wykonana przez:</p>
                <p class="text-lg text-gray-500"> Macieja Danika (264184) oraz Zuzannę Gorczycę (264182).</p>
            </div>

            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="{% url 'core:kontakt' %}" class="text-lg text-teal-500 hover:text-teal-700">Kontakt</a> </li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Warunki skorzystania z usługi</a> </li>
                    <li><a href="#" class="text-lg text-teal-500 hover:text-teal-700">Polityka prywatności</a> </li>
                </ul>
            </div>
        </footer>

    </body>
</html>

SnowRentals/core/templates/core/index.html
{% extends 'core/base.html' %}

{% block title %}Witaj{% endblock %}

{% block content %}
    <h1 class="w-1/4 mb-6 py-4 px-4 text-3xl font-semibold bg-teal-500 text-white rounded-xl">Strona główna</h1>
    {% if request.user.is_authenticated %}
        <h1 class="text-xl font-semibold">Zostałeś pomyślnie zalogowany! </h1>
    {% else %}
        <h1 class="text-xl font-semibold">Zaloguj się aby cokolwiek osiągnąć! </h1>
    {% endif %}

{% endblock %}

SnowRentals/core/templates/core/klient.html
{% extends 'core/base.html' %}

{% block title %}Klient{% endblock %}

{% block content %}
<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
    <h2 class="mb-12 text-2xl text-center">Lista klientów</h2>

    <div class="grid grid-cols-3 gap-3">
        {% for item in  items%}
        <div>
            <a href="{% url 'item:klient_szczegol' item.id %}">
                <div class="p-4 bg-white rounded-xl">
                    <h2 class="text-xl">{{ item.imie}} {{ item.nazwisko }}</h2>
                    <p class="text-gray-500">Nr telefonu: {{item.nr_telefonu}}</p>
                    <p class="text-gray-500">PESEL: {{item.PESEL}}</p>
                </div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

{% endblock %}

SnowRentals/core/templates/core/kontakt.html
{% extends 'core/base.html' %}

{% block title %}Kontakt{% endblock %}

{% block content %}
<h1 class="text-xl font-semibold">Maciej Danik - 264184@student.pwr.edu.pl </h1>
<h1 class="text-xl font-semibold">Zuzanna Gorczyca - 264182@student.pwr.edu.pl </h1>


{% endblock %}

SnowRentals/core/templates/core/login.html
{% extends 'core/base.html' %}

{% block title %}Zaloguj się{% endblock %}

{% block content %}
<div class="w-1/2 my-4 mx-auto p-4 bg-gray-100 rounded-xl">
    <h1 class="mb=4 font-semibold text-3xl">Zaloguj się</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Nazwa użytkownika:</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Hasło:</label><br>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_fiels_errors %}
            <div class="mb-3 p-4 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-3 px-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Zaloguj się</button>
    </form>
</div>


{% endblock %}

SnowRentals/core/templates/core/signup.html
{% extends 'core/base.html' %}

{% block title %}Nowy pracownik{% endblock %}

{% block content %}
<div class="w-1/2 my-4 mx-auto p-4 bg-gray-100 rounded-xl">
    <h1 class="mb=4 font-semibold text-3xl">Nowy pracownik</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Nazwa użytkownika:</label><br>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Imie:</label><br>
            {{ form.first_name }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Nazwisko:</label><br>
            {{ form.last_name }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Hasło:</label><br>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Powtórz hasło:</label><br>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_fiels_errors %}
            <div class="mb-3 p-4 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}

        <button class="py-3 px-4 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Dodaj</button>
    </form>
</div>


{% endblock %}

SnowRentals/core/templates/core/sprzet.html
{% extends 'core/base.html' %}

{% block title %}Sprzęt{% endblock %}

{% block content %}
    <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Lista sprzętu</h2>

            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                <div>
                    <a href="{% url 'item:sprzet_szczegol' item.id %}">
                        <div class="p-4 bg-white rounded-xl">
                            <h2 class="text-xl">{{ item.rodzaj }}</h2>
                            <p class="text-gray-500">Długość: {{ item.dlugosc }}</p>
                            <p class="text-gray-500">Stan: {{ item.stan }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
    </div>

{% endblock %}

SnowRentals/core/templates/core/utarg.html
{% extends 'core/base.html' %}

{% block title %}Utarg{% endblock %}

{% block content %}
   <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center"> Utarg</h2>

            <div class="grid grid-cols-3 gap-3">
                {% for items in item %}
                <div>
                        <div class="p-4 bg-white rounded-xl">
                            <h2 class="text-xl">{{ items.data}}</h2>
                            <p class="text-gray-500">Kwota: {{items.kwota}}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
    </div>
{% endblock %}

SnowRentals/core/templates/core/wypozyczenie.html
{% extends 'core/base.html' %}

{% block title %}Wypożyczenia{% endblock %}

{% block content %}
   <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center"> Trwające wypożyczenia</h2>

            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                <div>
                    <a href="{% url 'item:wypozyczenie_szczegol' item.id %}">
                        <div class="p-4 bg-white rounded-xl">
                            <h2 class="text-xl">{{ item.klient}}</h2>
                            <p class="text-gray-500">Od: {{item.od}}</p>
                            <p class="text-gray-500">Do: {{item.do}}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
    </div>

<div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
        <h2 class="mb-12 text-2xl text-center">Zakończone wypożyczenia</h2>

            <div class="grid grid-cols-3 gap-3">
                {% for item in oddane %}
                <div>
                    <a href="{% url 'item:wypozyczenie_szczegol' item.id  %}">
                        <div class="p-4 bg-white rounded-xl">
                            <h2 class="text-xl">{{ item.klient }}</h2>
                            <p class="text-gray-500">Długość: {{ item.od }}</p>
                            <p class="text-gray-500">Stan: {{ item.do }}</p>
                        </div>
                    </a>
                </div>
                {% endfor %}
            </div>
    </div>
{% endblock %}